### ISSUE TITLE
Add ability to auto get latest

### ISSUE THREAD

**Issue by CDuke** [CDuke/sublime-tfs#13]
Originally reported by: **Eric Ness (Bitbucket: [eric_ness](http://bitbucket.org/eric_ness), GitHub: [eric_ness](http://github.com/eric_ness))**

---

I'd love the ability to auto get latest before checkout. 

---
- Bitbucket: https://bitbucket.org/cduke/sublime-tfs/issue/13

**Comment by marknadig** [comment]
@CDuke I know this is an old issue. But, I've been testing this out with ST3 build 3103 and VS2015 on Windows 7. I confirmed Tools: Options: Source Control: VSTFS:  "Get latest version.. on checkout" is checked.  I confirmed checking out from a VS command line gets latest.  But if I rely on autocheckout, I'm not seeing the latest,

1. From VS, select a file, go to version history and select "get this version" from a prior changeset.
2. from ST3, open that file and type a comment. I do see the file is checked out, but I'm still seeing the older code. I would expect the file to reflect the latest version. I'm sure that could be a jerky UX, but that's what the user asked for when the said "get latest version on checkout".
