### ISSUE TITLE
Not able to Install the package thru Package Installer

### ISSUE THREAD

**Issue by kEpEx** [CDuke/sublime-tfs#24]
Not able to find the package thru Package Installer

![image](https://cloud.githubusercontent.com/assets/1455401/12494439/02d752b0-c03f-11e5-8edf-761941258a00.png)

**Comment by TT-Dev1** [comment]
Still an issue as of 2016-02-26.  Can I help?

**Comment by CDuke** [comment]
Add [pull request](https://github.com/wbond/package_control_channel/pull/5221)

**Comment by CDuke** [comment]
pull request merged
