### ISSUE TITLE
Does it work on MacOS X ?

### ISSUE THREAD

**Issue by jpvincent** [CDuke/sublime-tfs#26]
Hi

I installed the plugin and I see it integrated in Sublime.
I pointed the `tf_path` to the MacOS Path to tf (`TEE-CLC-14.0.3/tf` downloaded from https://www.microsoft.com/fr-FR/download/details.aspx?id=47727 ).
I know this utility is working because I managed to `tf get` my whole project from the CLI.

But when using this plugin, I dont manage to do anything : every command I run ends up after 20 seconds by "Unknown error". Nothing appears in the console

What did I miss ?

**Comment by CDuke** [comment]
Hi.
I do not have Mac, so I can not say anything about this. Maybe tf for Mac has another commands and arguments

**Comment by jpvincent** [comment]
The paths and the way to manage the path separators are different for sure, the API seems to be the same. Sorry if you can not test on a Mac, I would have thought that using Sublime on a Mac was more common than on Windows, where the MS stack is already greatly used for the TF users

Thanks anyway, we finally had to switch to Git for the non-windows users, and there is a backport of commits and all between TF and Git … More complex, but using TF from command line was horrible

**Comment by CDuke** [comment]
Ok.
So the problem is not relevant and can be closed
